# Generated by Django 2.2.12 on 2020-04-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='books',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='testapp.Book'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_categories', to='testapp.Category'),
        ),
    ]
